# Generated by Django 6.0.4 on 2026-04-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_state', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('recipe', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
