# Generated by Django 6.0.4 on 2026-05-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api', '0002_preferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Output',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
