# Generated by Django 6.0.4 on 2026-04-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api', '0003_alter_preferences_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='recipe',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
