# Generated by Django 6.0.4 on 2026-04-17 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api', '0004_alter_preferences_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='city_state',
            new_name='state',
        ),
    ]
