# Generated by Django 6.0.4 on 2026-04-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api', '0005_rename_city_state_preferences_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='input',
            field=models.CharField(max_length=255),
        ),
    ]
