# Generated by Django 6.0.4 on 2026-05-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.JSONField(blank=True, default=dict, null=True)),
                ('explanation', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
